package dev.wildware.composegl.demo.docs

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import dev.wildware.composegl.ui.debug.FrameBudget
import dev.wildware.composegl.ui.geometry.Offset
import dev.wildware.composegl.ui.input.GamepadButton
import dev.wildware.composegl.ui.input.GamepadId
import dev.wildware.composegl.ui.input.Key
import dev.wildware.composegl.ui.input.Modifiers
import dev.wildware.composegl.ui.input.PointerButton

/**
 * One picture for the documentation.
 *
 * The pictures in the wiki are taken from the real toolkit, on the real backend, through the real
 * skin — never drawn by hand. A hand-drawn diagram of a widget is a promise about what the widget
 * looks like, and it is wrong the first time somebody changes the widget and nobody remembers the
 * diagram. These are regenerated by running one command.
 *
 * @param name the file it becomes: `docs/wiki/images/<name>.png`.
 * @param pointer where to put the mouse, for a picture of a hover or a press. Null leaves it off
 *   the screen entirely, which is what an ordinary picture wants.
 * @param press whether that pointer is held down.
 * @param dragTo where to drag that pointer to, pressed at [pointer] and let go here, once, before
 *   the settling frames — for a picture of something a drag moved. Null drags nothing.
 * @param click whether that pointer clicks once, pressed and let go on the first frame, and then stays
 *   where it is. For a picture of what a click opens — a dropdown's list — which a held press never
 *   shows, because a click happens on the release.
 * @param button which button that click is made with: `Secondary` for a picture of a right-click menu.
 * @param then where the pointer goes a couple of frames after the click, and rests there — for a
 *   picture of what resting on something inside the opened thing opens, like a menu's submenu.
 * @param padCursor where to put a pad's cursor, for a picture of a `VirtualCursor`. The player is
 *   on a pad in that picture, so the arrow is drawn. Null leaves the pad out of it.
 * @param hold whether that drag stays pressed at [dragTo] instead of letting go, for a picture of
 *   something still being carried.
 * @param seconds how long to let the interface run before the shutter. Anything animated — a bar
 *   draining, a cooldown sweeping, a caret blinking — is a different picture at a different moment.
 * @param stock whether to take it through `Skin.Default` rather than the example's skin. For the
 *   pictures whose point is what you get before you have written a skin.
 * @param players how many players share the picture, split the way `Viewport.splitScreen` splits a
 *   window. Each gets their own interface, composed from [content] with [LocalDocPlayer] saying
 *   which player it is, and their own pad through one `InputRouter`: pad 0 is player one's.
 * @param pads buttons pressed before the shutter, through that router, so a picture of two players
 *   in two different places is the routing really putting them there.
 * @param padHold buttons pushed down before the shutter and never let go, so the picture is taken
 *   with a thumb still on them. For a picture of something that only happens while a button is
 *   held — a shoulder turning a colour picker's hue — which a press and a release never reaches.
 *   Give it [seconds] as well, or there is no time for the holding to do anything.
 * @param budget what the picture's frames are timed and traced with, for a picture of the frame
 *   budget overlay. Null gives the renderer its own.
 * @param focus whether focus is kept pointing at something, as a game's renderer does, so the
 *   picture opens with a widget focused. Off for every other picture, which wants no focus ring.
 * @param typed what a hand does at the keyboard before the shutter, a step to a frame, starting on
 *   the first frame that has been laid out. For a picture of something that only exists once it has
 *   been typed at — a console with a command half written in it. The picture is always given enough
 *   frames for the whole script and a few after it.
 */
internal class DocShot(
    val name: String,
    val width: Int,
    val height: Int,
    val pointer: Offset? = null,
    val press: Boolean = false,
    val dragTo: Offset? = null,
    val click: Boolean = false,
    val button: PointerButton = PointerButton.Primary,
    val then: Offset? = null,
    val padCursor: Offset? = null,
    val hold: Boolean = false,
    val seconds: Float = 0f,
    val stock: Boolean = false,
    val players: Int = 1,
    val pads: List<Pair<GamepadId, GamepadButton>> = emptyList(),
    val padHold: List<Pair<GamepadId, GamepadButton>> = emptyList(),
    val budget: FrameBudget? = null,
    val focus: Boolean = false,
    val typed: List<Typing> = emptyList(),
    val content: @Composable () -> Unit,
)

/**
 * One thing a hand does at the keyboard while a picture is being taken. See [DocShot.typed].
 *
 * Real events through the real router, the same as the pointer in these pictures: a console with a
 * half-written command in it is a console somebody really typed at, not a field handed a string.
 */
internal sealed interface Typing {

    /** A key pressed and let go, on one frame. */
    data class Press(val key: Key, val modifiers: Modifiers = Modifiers.None) : Typing

    /** Characters into whatever has focus, one a frame, the way a keyboard sends them. */
    data class Write(val text: String) : Typing

    /** Frames with nobody typing, so that what the step before started can finish: a slide, a fade. */
    data class Wait(val frames: Int) : Typing
}

/** Which player's interface is being composed, counting from zero, in a picture of several. */
internal val LocalDocPlayer = staticCompositionLocalOf { 0 }
