package dev.wildware.composegl.demo.docs

import androidx.compose.runtime.CompositionLocalProvider
import dev.wildware.composegl.demo.demoSkin
import dev.wildware.composegl.demo.demoSkinText
import dev.wildware.composegl.game.SubtitleSize
import dev.wildware.composegl.lwjgl3.GlCanvas
import dev.wildware.composegl.lwjgl3.GlTexture
import dev.wildware.composegl.lwjgl3.GlfwWindow
import dev.wildware.composegl.lwjgl3.StbFonts
import dev.wildware.composegl.ui.debug.FrameBudget
import dev.wildware.composegl.ui.focus.FocusManager
import dev.wildware.composegl.ui.graphics.ArtAtlas
import dev.wildware.composegl.ui.geometry.Offset
import dev.wildware.composegl.ui.geometry.Size
import dev.wildware.composegl.ui.host.UiHost
import dev.wildware.composegl.ui.host.UiRenderer
import dev.wildware.composegl.ui.input.GamepadCursor
import dev.wildware.composegl.ui.input.InputSource
import dev.wildware.composegl.ui.input.InputSourceTracker
import dev.wildware.composegl.ui.input.GamepadAxis
import dev.wildware.composegl.ui.input.GamepadEvent
import dev.wildware.composegl.ui.input.GamepadId
import dev.wildware.composegl.ui.input.GamepadNavigator
import dev.wildware.composegl.ui.input.InputRouter
import dev.wildware.composegl.ui.input.InputSink
import dev.wildware.composegl.ui.input.KeyEvent
import dev.wildware.composegl.ui.input.KeyEventType
import dev.wildware.composegl.ui.input.KeyNavigator
import dev.wildware.composegl.ui.input.KeyRouter
import dev.wildware.composegl.ui.input.PointerButton
import dev.wildware.composegl.ui.input.PointerEvent
import dev.wildware.composegl.ui.input.TextEvent
import dev.wildware.composegl.ui.input.PointerId
import dev.wildware.composegl.ui.input.PointerRouter
import dev.wildware.composegl.ui.layout.ScalePolicy
import dev.wildware.composegl.ui.layout.Viewport
import dev.wildware.composegl.ui.skin.Skin
import dev.wildware.composegl.ui.skin.SkinFormat
import dev.wildware.composegl.ui.text.FontProvider
import dev.wildware.composegl.ui.text.TextStyle
import dev.wildware.composegl.ui.text.scaledTextSizes
import dev.wildware.composegl.ui.widget.LocalFonts
import dev.wildware.composegl.ui.widget.ProvideGamepadCursor
import dev.wildware.composegl.ui.widget.ProvideInputSource
import dev.wildware.composegl.ui.skin.ProvideSkin
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.math.roundToInt
import org.lwjgl.BufferUtils
import org.lwjgl.opengl.GL11
import org.lwjgl.stb.STBTTFontinfo
import org.lwjgl.stb.STBTruetype

/**
 * Takes every picture in the wiki.
 *
 * `./gradlew :composegl-demo:docShots` writes them to `docs/wiki/images`. One hidden window, one
 * canvas, one skin, and a fresh interface per picture — so a picture is a photograph of the real
 * toolkit rather than a drawing of it, and the whole set is regenerated by one command when
 * something changes shape.
 *
 * Each picture is drawn in the bottom-left corner of the window at its own size and only that
 * rectangle is read back, which is the same trick the golden screenshots use.
 */
fun main() {
    val out = File(System.getenv("COMPOSEGL_DOC_SHOTS") ?: "docs/wiki/images")
    out.mkdirs()

    val window = GlfwWindow("composegl doc shots", Window, Window, visible = false, vsync = false)
    val art = GlTexture.decode(resource("ui/ui.png"))
    val coins = coinSheet()
    val pictures = atlas(art, coins)

    val fonts = StbFonts(pageSize = 1024)
    val typeface = resource("fonts/DejaVuSans.ttf")
    // Not a list of sizes anybody keeps up to date. Every skin these pictures are taken through is
    // read first for the sizes it declares, and each of those is baked again at every text scale a
    // picture asks for — so a style added to a skin file, or a picture taken through a skin nothing
    // has used yet, already has the font it needs. A missing one is not a blank label but a crash:
    // "no font for body at 14", four times over during one week of work, is why this is worked out.
    bakedSizes(listOf(Skin.Default, Skin.HighContrast, SkinFormat.read(demoSkinText(), pictures)))
        .forEach { (family, sizes) -> fonts.register(family, typeface, sizes) }

    // Where characters DejaVu's Latin does not cover come from, at every size anything above asks
    // for. Each fallback is registered with what its own file can actually draw rather than with a
    // list of the characters some picture happens to say today: the two Noto files are cuts holding
    // a few dozen characters each, and the Hebrew is DejaVu's own Hebrew block. So a new sentence in
    // any of these languages — and every form of a Hebrew letter, final nun included — is already
    // baked, and cannot turn up on the wiki as a row of empty boxes.
    val everySize = fonts.families().flatMap { fonts.sizesOf(it) }.distinct()
    val chinese = resource("fonts/NotoSansSC-Subset.ttf")
    val korean = resource("fonts/NotoSansKR-Subset.ttf")
    fonts.register("cjk", chinese, everySize, coverageOf(chinese, Everything))
    fonts.register("korean", korean, everySize, coverageOf(korean, Everything))
    fonts.register("hebrew", typeface, everySize, coverageOf(typeface, HebrewBlock))
    // And the emoji, as pictures, one per file in the resources folder: dropping a PNG in beside
    // them is all it takes to be able to say that emoji in a picture.
    fonts.registerPictures("emoji", emojiPictures(), everySize)
    fonts.fallBackTo(listOf("cjk", "korean", "hebrew", "emoji"))

    val canvas = GlCanvas(fonts)
    val skin = demoSkin(pictures, fonts)

    // Every picture, unless somebody working on one asked for just theirs: `COMPOSEGL_DOC_ONLY=dock`
    // takes the ones whose name holds "dock" and leaves the other few hundred alone.
    val only = System.getenv("COMPOSEGL_DOC_ONLY")

    try {
        docShots().filter { only == null || only in it.name }.forEach { shot ->
            if (shot.width > Window || shot.height > Window) {
                println("skipped ${shot.name}: ${shot.width}x${shot.height} needs COMPOSEGL_DOC_WINDOW")
                return@forEach
            }
            val file = File(out, "${shot.name}.png")
            save(file, take(shot, canvas, fonts, if (shot.stock) Skin.Default else skin.skin))
            println("wrote ${file.path}")
        }
    } finally {
        canvas.close()
        coins.close()
        art.close()
        fonts.close()
        window.close()
    }
}

/**
 * The art the skin file names, by region.
 *
 * The same three regions the example uses, because the pictures are taken through the example's
 * skin: what the wiki shows is what somebody running `:composegl-demo:runGl` sees.
 */
private fun atlas(art: GlTexture, coins: GlTexture) = ArtAtlas.of(
    mapOf(
        "panel" to art.region(0, 0, 48, 48),
        "ribbon" to art.region(52, 0, 24, 24),
        "icon/crest" to art.region(80, 0, 24, 24),
    ) + (0 until CoinFrames).associate { "coin_$it" to coins.region(it * CoinSize, 0, CoinSize, CoinSize) },
)

private const val CoinFrames = 8
private const val CoinSize = 32

/**
 * A coin turning on its edge, as one sheet of [CoinFrames] frames side by side.
 *
 * Drawn here rather than shipped as a picture so the sprite-animation shot has a real sheet to cut
 * up without adding art to the example: each frame is the coin squashed by how far it has turned,
 * with a darker back face and a rim.
 */
private fun coinSheet(): GlTexture {
    val width = CoinFrames * CoinSize
    val pixels = ByteArray(width * CoinSize * 4)
    val radius = 13f
    val centre = (CoinSize - 1) / 2f
    for (frame in 0 until CoinFrames) {
        val turn = kotlin.math.cos(frame * Math.PI / CoinFrames * 2).toFloat()
        val across = (radius * kotlin.math.abs(turn)).coerceAtLeast(2f)
        val face = if (turn >= 0f) 0xF2C14E else 0xC9952E
        for (y in 0 until CoinSize) {
            for (x in 0 until CoinSize) {
                val dx = x - centre
                val dy = y - centre
                if ((dx / across) * (dx / across) + (dy / radius) * (dy / radius) > 1f) continue
                val innerAcross = (across - 2f).coerceAtLeast(0.5f)
                val rim = (dx / innerAcross) * (dx / innerAcross) + (dy / (radius - 2f)) * (dy / (radius - 2f)) > 1f
                val shine = turn >= 0f && !rim && dx < -across * 0.2f && dx > -across * 0.5f
                val colour = when {
                    rim -> 0x8A5A12
                    shine -> 0xFFE9A8
                    else -> face
                }
                val at = (y * width + frame * CoinSize + x) * 4
                pixels[at] = (colour shr 16).toByte()
                pixels[at + 1] = (colour shr 8).toByte()
                pixels[at + 2] = colour.toByte()
                pixels[at + 3] = 0xFF.toByte()
            }
        }
    }
    return GlTexture.rgba(width, CoinSize, pixels, smooth = false)
}

private fun resource(path: String): ByteArray =
    checkNotNull(object {}.javaClass.classLoader.getResourceAsStream(path)) { "no $path on the classpath" }
        .use { it.readBytes() }

/**
 * Every font size the pictures are going to ask for, by family: each size a skin declares, baked
 * again at each of [DocTextScales] and each subtitle preset.
 *
 * Read off the skins rather than written down here, because the two kept drifting apart and the
 * drift is a crash rather than something a person notices. A skin is parsed for this with no fonts
 * and no art of its own — the file is the whole answer, and it can be read long before there is a
 * font to measure with.
 *
 * Every scale is applied to every family. A family is a handful of sizes and the sizes overlap, so
 * working out which scale reaches which style is more arithmetic than it would save.
 */
private fun bakedSizes(skins: List<Skin>): Map<String, List<Int>> {
    val scales = (DocTextScales + SubtitleSize.scales + 1f).distinct()
    val declared = LinkedHashMap<String, MutableSet<Int>>()
    // A widget nothing styled draws at the toolkit's own default, which no skin file has to mention.
    fun take(style: TextStyle?) {
        if (style == null) return
        declared.getOrPut(style.family) { LinkedHashSet() } += style.size.roundToInt()
    }
    take(TextStyle())
    skins.forEach { skin ->
        take(skin.defaults?.textStyle)
        skin.styles.values.forEach { style ->
            listOf(style.base, style.hovered, style.focused, style.pressed, style.disabled)
                .forEach { take(it?.textStyle) }
        }
    }
    return declared.mapValues { (_, sizes) -> scaledTextSizes(sizes, scales) }
}

/**
 * The characters [ttf] can really draw, within [range], as the ranges a font is registered with.
 *
 * Asked of the file rather than listed by hand. The two Noto files here are cuts holding a few
 * dozen characters each, so "everything in the file" is the right set for them; DejaVu holds
 * thousands, so its Hebrew is asked for by block.
 */
private fun coverageOf(ttf: ByteArray, range: IntRange): List<IntRange> {
    val bytes = BufferUtils.createByteBuffer(ttf.size).put(ttf)
    bytes.flip()
    val info = STBTTFontinfo.create()
    check(STBTruetype.stbtt_InitFont(info, bytes)) { "that is not a font this can read" }
    val found = ArrayList<IntRange>()
    var start = -1
    for (codepoint in range) {
        val has = STBTruetype.stbtt_FindGlyphIndex(info, codepoint) != 0
        if (has && start < 0) start = codepoint
        if (!has && start >= 0) {
            found += start until codepoint
            start = -1
        }
    }
    if (start >= 0) found += start..range.last
    check(found.isNotEmpty()) { "that font has nothing in $range" }
    return found
}

/**
 * The emoji, one per PNG in the `emoji` resource folder, under the character each one draws.
 *
 * `emoji_u1f44d.png` is 👍. Listing the folder rather than naming the six files means a new emoji in
 * a picture is a file dropped in beside the others, with nothing here to remember.
 */
private fun emojiPictures(): Map<String, ByteArray> {
    val folder = checkNotNull(object {}.javaClass.classLoader.getResource("emoji")) { "no emoji on the classpath" }
    val files = checkNotNull(File(folder.toURI()).listFiles()) { "$folder is not a folder to list" }
    return files.filter { it.name.endsWith(".png") }
        .sortedBy { it.name }
        .associate { file ->
            val codepoints = file.name.removeSuffix(".png").split('_')
                .filter { it.startsWith("u") }
                .map { it.removePrefix("u").toInt(16) }
            require(codepoints.isNotEmpty()) { "${file.name} is not named emoji_u<hex>" }
            codepoints.joinToString("") { String(Character.toChars(it)) } to file.readBytes()
        }
}

/** Every character a font file might hold that these pictures could want: the whole of the BMP. */
private val Everything = 0x20..0xFFFF

/** Hebrew, as Unicode has it: the letters, their final forms, the points and the punctuation. */
private val HebrewBlock = 0x0590..0x05FF

/**
 * The window every picture is drawn inside, and the largest a picture can be.
 *
 * Its size reaches the driver, and a different one moves a pixel here and there in every picture
 * taken in it, so it stays where it is and a picture too big for it is skipped with a line saying
 * so. `COMPOSEGL_DOC_WINDOW=1280 COMPOSEGL_DOC_ONLY=art-sheet` takes that one in a window of its
 * own, which is how the pictures wider than this are taken.
 */
private val Window = System.getenv("COMPOSEGL_DOC_WINDOW")?.toIntOrNull() ?: 640

/** Frames drawn before the shutter, so that anything with a first-frame animation has settled. */
internal const val Settle = 3

/** The frames after a click on which the pointer moves on to a shot's `then`. */
private val ThenFrames = 2..3

/** How many moves a doc shot's drag is made of. */
private const val DragSteps = 12

/** Sixty a second, which is the rate every animation in the toolkit is written against. */
private const val FrameNanos = 16_666_666L

private fun take(shot: DocShot, canvas: GlCanvas, fonts: FontProvider, skin: Skin): BufferedImage {
    val window = Size(shot.width.toFloat(), shot.height.toFloat())
    // One player is an ordinary picture; several share the window the way a local co-op game does.
    val viewports = if (shot.players == 1) {
        listOf(Viewport(design = window, physical = window, policy = ScalePolicy.Fit))
    } else {
        Viewport.splitScreen(
            design = Size(shot.width.toFloat() / 2f, shot.height.toFloat()),
            physical = window,
            players = shot.players,
        )
    }

    val hosts = viewports.map { UiHost() }

    // Real input rather than a widget told to look hovered: a picture of a hover is only worth
    // having if it is the state the toolkit actually reaches when a mouse is there.
    val focuses = hosts.map { FocusManager(it.root) }
    val pointers = hosts.indices.map { PointerRouter(hosts[it].root, focuses[it]) }
    val pads = focuses.map { GamepadNavigator(it) }
    val mouse = pointers[0]

    // The same for a pad's cursor: a real one, moved and framed as a game would, on a player who is
    // on a pad — which is the only time the arrow is drawn.
    val cursor = GamepadCursor(hosts[0].root, mouse)

    hosts.forEachIndexed { player, host ->
        host.setContent {
            CompositionLocalProvider(LocalFonts provides fonts, LocalDocPlayer provides player) {
                ProvideSkin(skin) {
                    if (shot.padCursor == null || player != 0) {
                        shot.content()
                    } else {
                        ProvideInputSource(InputSourceTracker(InputSource.Gamepad)) {
                            ProvideGamepadCursor(cursor) { shot.content() }
                        }
                    }
                }
            }
        }
    }

    // Each player's pad through one router, as a split-screen game has it: pad 0 is player one's.
    val router = InputRouter()
    hosts.indices.forEach { player ->
        router.assignGamepad(GamepadId(player), object : InputSink {
            override fun onPointer(event: PointerEvent) = pointers[player].onPointer(event)
            override fun onKey(event: KeyEvent) = false
            override fun onText(event: TextEvent) = false
            override fun onGamepad(event: GamepadEvent) = pads[player].onGamepad(event)
        })
    }

    val renderers = hosts.indices.map { player ->
        // Focus is drawn only where a pad moved it: the split-screen picture is about whose focus
        // is where, and every other picture shows its widgets the way they look before anyone
        // reaches for a pad, except a picture that asks for focus to be kept, as a game's renderer does.
        // A picture with typing in it keeps it too: typed characters go to whatever has focus, and
        // nothing has any until the renderer has been given a focus manager to refresh.
        // A script that only holds a key down is not typing at anything: a held Shift is heard
        // wherever focus is, including nowhere, so a picture of a mouse keeps its ringless bag.
        val types = shot.typed.any { it is Typing.Press || it is Typing.Write }
        val kept = shot.players > 1 || shot.focus || types
        UiRenderer(hosts[player], canvas, shot.budget?.takeIf { player == 0 } ?: FrameBudget()).also { if (kept) it.focus = focuses[player] }
    }
    // The keyboard, wired the way a game wires it: whatever has focus first, the shortcut layer
    // inside the router after it, and navigation for the keys nobody wanted. Player one's, since a
    // picture of typing is a picture of one pair of hands.
    val keys = KeyRouter(focuses[0], hosts[0].root)
    val navigator = KeyNavigator(focuses[0])

    // A key down and up, offered to the focused widget and then to navigation, as a backend does it.
    val press: (KeyEvent) -> Unit = { event -> if (!keys.onKey(event)) navigator.onKey(event) }
    val write: (Char) -> Unit = { character -> keys.onText(TextEvent(character.toString())) }

    // The shot's script, flattened to one thing a frame: a key, a character, or nothing at all.
    val typing: List<() -> Unit> = shot.typed.flatMap { step ->
        when (step) {
            is Typing.Press -> listOf({
                press(KeyEvent(step.key, KeyEventType.Down, step.modifiers))
                press(KeyEvent(step.key, KeyEventType.Up, step.modifiers))
            })
            is Typing.Hold -> listOf({ press(KeyEvent(step.key, KeyEventType.Down, step.modifiers)) })
            is Typing.Write -> step.text.map { character -> { write(character) } }
            is Typing.Wait -> List(step.frames) { {} }
        }
    }
    var typed = 0

    // The same, for the pad: one push or one button a frame, through the same router the buttons
    // above go through, so a stick in a picture is a stick a player really moved.
    val pushes: List<() -> Unit> = shot.padded.flatMap { step ->
        when (step) {
            is Padding.Push -> {
                val horizontal = if (step.stick == DocStick.Left) GamepadAxis.LeftX else GamepadAxis.RightX
                val vertical = if (step.stick == DocStick.Left) GamepadAxis.LeftY else GamepadAxis.RightY
                listOf({
                    router.onGamepad(GamepadEvent.Axis(step.pad, horizontal, step.x))
                    router.onGamepad(GamepadEvent.Axis(step.pad, vertical, step.y))
                })
            }
            is Padding.Down -> listOf({ router.onGamepad(GamepadEvent.ButtonDown(step.pad, step.button)) })
            is Padding.Up -> listOf({ router.onGamepad(GamepadEvent.ButtonUp(step.pad, step.button)) })
            is Padding.Wait -> List(step.frames) { {} }
        }
    }
    var pushed = 0

    // And the same for a picture that takes more than one drag: one whole gesture a frame, so the
    // one before it has been composed and laid out before the next one is asked what it is over.
    val gestures: List<() -> Unit> = shot.drags.flatMap { step ->
        when (step) {
            is Dragging.Drag -> listOf({ drag(mouse, step.from, step.to, step.hold) })
            is Dragging.Carry -> listOf({
                mouse.onPointer(PointerEvent.Move(PointerId.Mouse, step.to, setOf(PointerButton.Primary)))
            })
            is Dragging.Wait -> List(step.frames) { {} }
        }
    }
    var gestured = 0

    // After layout, because a pointer lands on whatever is under it and nothing is anywhere until
    // the tree has been measured.
    var dragged = false
    var clicked = false
    var wheeled = false
    var sinceClick = 0
    renderers[0].onLaidOut = { nanos ->
        shot.padCursor?.let { at ->
            cursor.moveTo(at)
            cursor.frame(nanos / 1_000_000L)
        }
        val to = shot.dragTo
        shot.pointer?.let { at ->
            // The wheel first, once, so a picture of a zoomed camera is one a real wheel zoomed:
            // the toolkit takes a notch towards the screen as a negative delta.
            if (shot.wheel != 0 && !wheeled) {
                wheeled = true
                mouse.onPointer(PointerEvent.Move(PointerId.Mouse, at))
                val notch = Offset(0f, if (shot.wheel > 0) -1f else 1f)
                repeat(kotlin.math.abs(shot.wheel)) { mouse.onPointer(PointerEvent.Scroll(PointerId.Mouse, at, notch)) }
            }
            val then = shot.then
            if (to == null && clicked && then != null) {
                // A few frames after the click, so what it opened is laid out to land on, and then left
                // alone rather than moved every frame, because a rest is measured from the last move.
                sinceClick++
                if (sinceClick in ThenFrames) mouse.onPointer(PointerEvent.Move(PointerId.Mouse, then))
            } else if (to == null) {
                mouse.onPointer(PointerEvent.Move(PointerId.Mouse, at))
                if (shot.press) mouse.onPointer(PointerEvent.Press(PointerId.Mouse, at))
                // Once, not every frame: a click every frame on a dropdown opens and closes it in turn.
                if (shot.click && !clicked) {
                    clicked = true
                    mouse.onPointer(PointerEvent.Press(PointerId.Mouse, at, shot.button))
                    mouse.onPointer(PointerEvent.Release(PointerId.Mouse, at, shot.button))
                }
            } else if (!dragged) {
                // Once, in steps, the way a hand does it: a drag is a gesture rather than a state,
                // and pressing again every frame would be a new one each time.
                dragged = true
                drag(mouse, at, to, shot.hold)
            }
        }
        // One whole drag a frame, for a picture that takes several.
        if (gestured < gestures.size) gestures[gestured++]()
        // One step of the typing a frame, so each one is composed and laid out before the next: a
        // Tab has a word to finish, and an Enter has a line to run.
        if (typed < typing.size) typing[typed++]()
        // And one step of the pad's, for the same reason: a wheel has to compose with the push it
        // was given before it can be asked what the next one points at.
        if (pushed < pushes.size) pushes[pushed++]()
    }

    try {
        // Long enough for the whole script and a few frames after it, so a picture never catches a
        // shot in the middle of its own typing because somebody forgot to ask for the seconds.
        val frames = maxOf(
            shot.still + (shot.seconds * 60f).toInt(),
            typing.size + shot.still,
            pushes.size + shot.still,
            gestures.size + shot.still,
        )
        for (frame in 0..frames) {
            GL11.glClearColor(0f, 0f, 0f, 1f)
            GL11.glClear(GL11.GL_COLOR_BUFFER_BIT)
            renderers.forEachIndexed { player, ui -> ui.render(viewports[player], frame * FrameNanos) }
            // Once focus has settled on something, so a step moves it from somewhere.
            if (frame == 1) {
                shot.pads.forEach { (pad, button) ->
                    router.onGamepad(GamepadEvent.ButtonDown(pad, button))
                    router.onGamepad(GamepadEvent.ButtonUp(pad, button))
                }
                // Down and left down, so the rest of the frames are taken with a thumb still on it and
                // whatever repeats while it is held goes on repeating up to the shutter.
                shot.padHold.forEach { (pad, button) -> router.onGamepad(GamepadEvent.ButtonDown(pad, button)) }
            }
        }
        return read(shot.width, shot.height)
    } finally {
        hosts.forEach { it.dispose() }
    }
}

/**
 * One drag: pressed at [from], carried to [to] in [DragSteps] moves, and let go unless [hold].
 *
 * A gesture rather than a state. The moves are what a widget hears while a hand carries something,
 * so a window in one of these pictures really was dragged across the screen to where it is. The
 * press needs no move before it: the router hit-tests a press where the press is.
 */
private fun drag(mouse: PointerRouter, from: Offset, to: Offset, hold: Boolean) {
    mouse.onPointer(PointerEvent.Press(PointerId.Mouse, from))
    for (step in 1..DragSteps) {
        val along = from + (to - from) * (step / DragSteps.toFloat())
        mouse.onPointer(PointerEvent.Move(PointerId.Mouse, along, setOf(PointerButton.Primary)))
    }
    if (!hold) mouse.onPointer(PointerEvent.Release(PointerId.Mouse, to))
}

/** The bottom-left corner of the framebuffer, turned the right way up. */
private fun read(width: Int, height: Int): BufferedImage {
    val bytes = BufferUtils.createByteBuffer(width * height * 4)
    GL11.glReadPixels(0, 0, width, height, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, bytes)

    val image = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
    for (y in 0 until height) {
        for (x in 0 until width) {
            // OpenGL hands back the bottom row first.
            val at = ((height - 1 - y) * width + x) * 4
            image.setRGB(
                x,
                y,
                (bytes.get(at).toInt() and 0xFF shl 16) or
                    (bytes.get(at + 1).toInt() and 0xFF shl 8) or
                    (bytes.get(at + 2).toInt() and 0xFF),
            )
        }
    }
    return image
}

private fun save(file: File, image: BufferedImage) {
    ImageIO.write(image, "png", file)
}
