package dev.wildware.composegl.demo.docs

import androidx.compose.runtime.CompositionLocalProvider
import dev.wildware.composegl.demo.demoSkin
import dev.wildware.composegl.lwjgl3.GlCanvas
import dev.wildware.composegl.lwjgl3.GlTexture
import dev.wildware.composegl.lwjgl3.GlfwWindow
import dev.wildware.composegl.lwjgl3.StbFonts
import dev.wildware.composegl.ui.focus.FocusManager
import dev.wildware.composegl.ui.graphics.ArtAtlas
import dev.wildware.composegl.ui.geometry.Size
import dev.wildware.composegl.ui.host.UiHost
import dev.wildware.composegl.ui.host.UiRenderer
import dev.wildware.composegl.ui.input.PointerButton
import dev.wildware.composegl.ui.input.PointerEvent
import dev.wildware.composegl.ui.input.PointerId
import dev.wildware.composegl.ui.input.PointerRouter
import dev.wildware.composegl.ui.layout.ScalePolicy
import dev.wildware.composegl.ui.layout.Viewport
import dev.wildware.composegl.ui.skin.Skin
import dev.wildware.composegl.ui.text.FontProvider
import dev.wildware.composegl.ui.text.scaledTextSizes
import dev.wildware.composegl.ui.widget.LocalFonts
import dev.wildware.composegl.ui.skin.ProvideSkin
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import org.lwjgl.BufferUtils
import org.lwjgl.opengl.GL11

/**
 * Takes every picture in the wiki.
 *
 * `./gradlew :composegl-demo:docShots` writes them to `docs/wiki/images`. One hidden window, one
 * canvas, one skin, and a fresh interface per picture — so a picture is a photograph of the real
 * toolkit rather than a drawing of it, and the whole set is regenerated by one command when
 * something changes shape.
 *
 * Each picture is drawn in the bottom-left corner of the window at its own size and only that
 * rectangle is read back, which is the same trick the golden screenshots use.
 */
fun main() {
    val out = File(System.getenv("COMPOSEGL_DOC_SHOTS") ?: "docs/wiki/images")
    out.mkdirs()

    val window = GlfwWindow("composegl doc shots", Window, Window, visible = false, vsync = false)
    val fonts = StbFonts(pageSize = 1024)
    val typeface = resource("fonts/DejaVuSans.ttf")
    // Every size again at 125% and 150%, for the picture of the text size setting.
    fonts.register("body", typeface, scaledTextSizes(listOf(12, 13, 16, 20), listOf(1f, 1.25f, 1.5f)))
    fonts.register("display", typeface, listOf(34))
    // What the toolkit's own skin asks for, for the pictures taken without the example's skin.
    fonts.register("default", typeface, listOf(12, 13, 14, 16, 18, 22, 26))

    val art = GlTexture.decode(resource("ui/ui.png"))
    val coins = coinSheet()
    val canvas = GlCanvas(fonts)
    val skin = demoSkin(atlas(art, coins), fonts)

    try {
        docShots().forEach { shot ->
            val file = File(out, "${shot.name}.png")
            save(file, take(shot, canvas, fonts, if (shot.stock) Skin.Default else skin.skin))
            println("wrote ${file.path}")
        }
    } finally {
        canvas.close()
        coins.close()
        art.close()
        fonts.close()
        window.close()
    }
}

/**
 * The art the skin file names, by region.
 *
 * The same three regions the example uses, because the pictures are taken through the example's
 * skin: what the wiki shows is what somebody running `:composegl-demo:runGl` sees.
 */
private fun atlas(art: GlTexture, coins: GlTexture) = ArtAtlas.of(
    mapOf(
        "panel" to art.region(0, 0, 48, 48),
        "ribbon" to art.region(52, 0, 24, 24),
        "icon/crest" to art.region(80, 0, 24, 24),
    ) + (0 until CoinFrames).associate { "coin_$it" to coins.region(it * CoinSize, 0, CoinSize, CoinSize) },
)

private const val CoinFrames = 8
private const val CoinSize = 32

/**
 * A coin turning on its edge, as one sheet of [CoinFrames] frames side by side.
 *
 * Drawn here rather than shipped as a picture so the sprite-animation shot has a real sheet to cut
 * up without adding art to the example: each frame is the coin squashed by how far it has turned,
 * with a darker back face and a rim.
 */
private fun coinSheet(): GlTexture {
    val width = CoinFrames * CoinSize
    val pixels = ByteArray(width * CoinSize * 4)
    val radius = 13f
    val centre = (CoinSize - 1) / 2f
    for (frame in 0 until CoinFrames) {
        val turn = kotlin.math.cos(frame * Math.PI / CoinFrames * 2).toFloat()
        val across = (radius * kotlin.math.abs(turn)).coerceAtLeast(2f)
        val face = if (turn >= 0f) 0xF2C14E else 0xC9952E
        for (y in 0 until CoinSize) {
            for (x in 0 until CoinSize) {
                val dx = x - centre
                val dy = y - centre
                if ((dx / across) * (dx / across) + (dy / radius) * (dy / radius) > 1f) continue
                val innerAcross = (across - 2f).coerceAtLeast(0.5f)
                val rim = (dx / innerAcross) * (dx / innerAcross) + (dy / (radius - 2f)) * (dy / (radius - 2f)) > 1f
                val shine = turn >= 0f && !rim && dx < -across * 0.2f && dx > -across * 0.5f
                val colour = when {
                    rim -> 0x8A5A12
                    shine -> 0xFFE9A8
                    else -> face
                }
                val at = (y * width + frame * CoinSize + x) * 4
                pixels[at] = (colour shr 16).toByte()
                pixels[at + 1] = (colour shr 8).toByte()
                pixels[at + 2] = colour.toByte()
                pixels[at + 3] = 0xFF.toByte()
            }
        }
    }
    return GlTexture.rgba(width, CoinSize, pixels, smooth = false)
}

private fun resource(path: String): ByteArray =
    checkNotNull(object {}.javaClass.classLoader.getResourceAsStream(path)) { "no $path on the classpath" }
        .use { it.readBytes() }

/** The window every picture is drawn inside. Bigger than the biggest of them. */
private const val Window = 640

/** Frames drawn before the shutter, so that anything with a first-frame animation has settled. */
private const val Settle = 3

/** How many moves a doc shot's drag is made of. */
private const val DragSteps = 12

/** Sixty a second, which is the rate every animation in the toolkit is written against. */
private const val FrameNanos = 16_666_666L

private fun take(shot: DocShot, canvas: GlCanvas, fonts: FontProvider, skin: Skin): BufferedImage {
    val host = UiHost()
    host.setContent {
        CompositionLocalProvider(LocalFonts provides fonts) {
            ProvideSkin(skin) { shot.content() }
        }
    }

    // Real input rather than a widget told to look hovered: a picture of a hover is only worth
    // having if it is the state the toolkit actually reaches when a mouse is there.
    val focus = FocusManager(host.root)
    val router = PointerRouter(host.root, focus)

    val viewport = Viewport(
        design = Size(shot.width.toFloat(), shot.height.toFloat()),
        physical = Size(shot.width.toFloat(), shot.height.toFloat()),
        policy = ScalePolicy.Fit,
    )

    val ui = UiRenderer(host, canvas)
    // After layout, because a pointer lands on whatever is under it and nothing is anywhere until
    // the tree has been measured.
    var dragged = false
    ui.onLaidOut = {
        val to = shot.dragTo
        shot.pointer?.let { at ->
            if (to == null) {
                router.onPointer(PointerEvent.Move(PointerId.Mouse, at))
                if (shot.press) router.onPointer(PointerEvent.Press(PointerId.Mouse, at))
            } else if (!dragged) {
                // Once, in steps, the way a hand does it: a drag is a gesture rather than a state,
                // and pressing again every frame would be a new one each time.
                dragged = true
                router.onPointer(PointerEvent.Press(PointerId.Mouse, at))
                for (step in 1..DragSteps) {
                    val along = at + (to - at) * (step / DragSteps.toFloat())
                    router.onPointer(PointerEvent.Move(PointerId.Mouse, along, setOf(PointerButton.Primary)))
                }
                router.onPointer(PointerEvent.Release(PointerId.Mouse, to))
            }
        }
    }

    try {
        val frames = Settle + (shot.seconds * 60f).toInt()
        for (frame in 0..frames) {
            GL11.glClearColor(0f, 0f, 0f, 1f)
            GL11.glClear(GL11.GL_COLOR_BUFFER_BIT)
            ui.render(viewport, frame * FrameNanos)
        }
        return read(shot.width, shot.height)
    } finally {
        host.dispose()
    }
}

/** The bottom-left corner of the framebuffer, turned the right way up. */
private fun read(width: Int, height: Int): BufferedImage {
    val bytes = BufferUtils.createByteBuffer(width * height * 4)
    GL11.glReadPixels(0, 0, width, height, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, bytes)

    val image = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
    for (y in 0 until height) {
        for (x in 0 until width) {
            // OpenGL hands back the bottom row first.
            val at = ((height - 1 - y) * width + x) * 4
            image.setRGB(
                x,
                y,
                (bytes.get(at).toInt() and 0xFF shl 16) or
                    (bytes.get(at + 1).toInt() and 0xFF shl 8) or
                    (bytes.get(at + 2).toInt() and 0xFF),
            )
        }
    }
    return image
}

private fun save(file: File, image: BufferedImage) {
    ImageIO.write(image, "png", file)
}
