package composegl.demo.docs

import androidx.compose.runtime.Composable
import composegl.ui.geometry.Offset

/**
 * One picture for the documentation.
 *
 * The pictures in the wiki are taken from the real toolkit, on the real backend, through the real
 * skin — never drawn by hand. A hand-drawn diagram of a widget is a promise about what the widget
 * looks like, and it is wrong the first time somebody changes the widget and nobody remembers the
 * diagram. These are regenerated by running one command.
 *
 * @param name the file it becomes: `docs/wiki/images/<name>.png`.
 * @param pointer where to put the mouse, for a picture of a hover or a press. Null leaves it off
 *   the screen entirely, which is what an ordinary picture wants.
 * @param press whether that pointer is held down.
 * @param seconds how long to let the interface run before the shutter. Anything animated — a bar
 *   draining, a cooldown sweeping, a caret blinking — is a different picture at a different moment.
 * @param stock whether to take it through `Skin.Default` rather than the example's skin. For the
 *   pictures whose point is what you get before you have written a skin.
 */
internal class DocShot(
    val name: String,
    val width: Int,
    val height: Int,
    val pointer: Offset? = null,
    val press: Boolean = false,
    val seconds: Float = 0f,
    val stock: Boolean = false,
    val content: @Composable () -> Unit,
)
